### PR TITLE
feat(delivery): speed up setup by parallelizing builds

### PR DESCRIPTION
**Pull request by ace-n**
Extracted from #482

### CODE REVIEW

**Comment by grayside** [comment]
Instead of the bash syntax, would `wait` work with `--async`? In either case, does this suppress or scramble build output?

**Comment by grayside** [comment]
Also, if a build fails will setup.sh still fail?

**Comment by ace-n** [comment]
I have not tried the `wait` approach, but this does **not** affect build output.

I haven't tested the script-wide failure though.

**Comment by grayside** [comment]
To be clear, I'm suggesting `gcloud builds submit --async`, with `wait` to pause the script until all builds complete, but I'm concerned the build logs will interleave or be missing, and in that case we need to decide if that's a problem.

**Comment by ace-n** [comment]
Yes - I was concerned about interleaving too. I verified that didn't happen with this implementation.

**Comment by ace-n** [comment]
Closing in favor of #529

**Pull request closed without merging**
