### PR TITLE
feat(ops): add testing image

### PR DESCRIPTION
**Pull request by ace-n**
This will be necessary to test the `Delivery` component.

Part of #347

### CODE REVIEW

**Comment by ace-n** [comment]
Not entirely sure what you mean - my goal here is to _test the setup process_.

**Comment by ace-n** [comment]
Also - the main reason I'm combining these tools together is to avoid the legwork of an additional Docker image CI/CD pipeline.

(I'm torn on whether the additional `separation of concerns` two images would provide us justifies the extra work.)

**Comment by grayside** [comment]
What is the overhead in:

* Step 1: Run setup
* Step 2: Test setup

**Comment by ace-n** [comment]
I was planning to (re)use this image in (those) two separate build steps.

I'm intending for the setup-vs-test split to be at the **Cloud Build** layer, not the Dockerfile layer.

**Comment by grayside** [comment]
Can we split at the Dockerfile layer as well? Giant dockerfiles with many dependencies are an antipattern.

**Comment by ace-n** [comment]
@grayside this is now in its own Docker image.

**Review by grayside — APPROVED** [review]

**Pull request merged**
