### PR TITLE
feat!: reorganize installation testing TF + add builds

### PR DESCRIPTION
**Pull request by ace-n**
- Added a `data.tf` file, and moved the `google_project` resource there
- Added Cloud Build triggers for _Delivery Image building_ (`presubmit`) and _Installation Testing_ (`nightly`).
- Renamed the (mostly IAM resource-based) `delivery_testing.tf` file to `iam.tf`

✅  I've tested this, and all triggers are passing.

### CODE REVIEW

**Review by grayside — COMMENTED** [review]
This generally seems good, but want to check: are we using the same pub/sub topic for both nightly system and deployment tests? Are there any shared resources that could end up in contention?

**Comment by ace-n** [comment]
The website system tests are **not** currently running nightly; rather, they run against `localhost` upon presubmit.

That said, building and testing resources on the same topic **can** cause race conditions (primarily, using the previous day's artifacts in test runs).

I'd argue that we should consider address the race condition issue in a **follow-on PR** by **creating two separate topics** - `nightly_builds` and `nightly_tests`, where the latter runs ~1 hour after the former.

**Comment by grayside** [comment]
Let's explore that as a follow-up design discussion. For now it sounds like this is not a source of conflicts.

**Comment by ace-n** [comment]
@grayside filed as #533

**Review by grayside — APPROVED** [review]

**Pull request merged**
